<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- 1. For Local Devs: Only test the newest modern framework and legacy framework -->
    <TargetFrameworks Condition="'$(CI)' != 'true'">net48;net481;net8.0</TargetFrameworks>
    
    <!-- 2. For the CI/CD Server: Test absolutely everything -->
    <TargetFrameworks Condition="'$(CI)' == 'true'">net48;net481;net6.0;net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <!-- Silences the warnings about using v10.x NuGet packages on net6.0 -->
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>

    <!-- Silences the EOL warning for net6.0 -->
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChronoStack\ChronoStack.csproj" />
  </ItemGroup>

</Project>
